# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb13f907ab157e550b32f43e42d9b4a05a4b0da39c59213ce33d47a8b9d6a567035001878a094587874f2b4e9f179d234ae22cfb322a9aed7087bd4ea188326

test:
  secret_key_base: 6b74cec8d3850ffd419934703e5251a3676a70c159999603a7f18d0a5f3d40e0284bf53b5b91eaefad047392f32dab34db03d3e5526fd6f6bbd026230e43147e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
